CREATE TABLE Users (
	userId INT(11) NOT NULL AUTO_INCREMENT,
    name VARCHAR(45) DEFAULT NULL,
    email VARCHAR(45) DEFAULT NULL,
    password VARCHAR(150) DEFAULT NULL,
    PRIMARY KEY(UserId)
) ENGINE=InnoDB AUTO_INCREMENT=0;

DESCRIBE USERS;

SELECT * FROM USERS;

DROP TABLE USERS;

CREATE TABLE Posts (
	postId INT(11) NOT NULL AUTO_INCREMENT,
    postname VARCHAR(45) DEFAULT NULL,
    description VARCHAR(200) DEFAULT NULL,
    createdBy VARCHAR(11) DEFAULT NULL,
    PRIMARY KEY(postId)
)ENGINE=InnoDB AUTO_INCREMENT=0;

DESCRIBE POSTS;

SELECT * FROM POSTS;